name: dart_web_boilerplate
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.9.2"
  flutter: '>=3.35.6'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  smvp_dart:
    git:
      url: https://github.com/sl8s/smvp.git
      ref: v1.0.1
      path: packages/smvp_dart
  meta: ^1.16.0
  intl: ^0.20.2
  responsive_framework: ^1.5.1
  go_router: ^16.2.1
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.1
  http: ^1.5.0

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.26.3

flutter:
  assets:
    - assets/icons/desktop/app_icon.ico
    - assets/icons/large_desktop/app_icon.ico
    - assets/icons/large_tablet/app_icon.ico
    - assets/icons/mobile/app_icon.ico
    - assets/icons/tablet/app_icon.ico
    - assets/icons/tv/app_icon.ico
    - assets/images/desktop/app_icon.png
    - assets/images/large_desktop/app_icon.png
    - assets/images/large_tablet/app_icon.png
    - assets/images/mobile/app_icon.png
    - assets/images/tablet/app_icon.png
    - assets/images/tv/app_icon.png
    - assets/images/dev.png
    ## Don't forget to comment out the this line so that the tests in GitHub Action are successful.
    ##- assets/.env
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_18pt_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/inter_24pt_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/inter_28pt_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/inter_18pt_medium.ttf
          weight: 500
        - asset: assets/fonts/inter_24pt_medium.ttf
          weight: 500
        - asset: assets/fonts/inter_28pt_medium.ttf
          weight: 500
        - asset: assets/fonts/inter_18pt_regular.ttf
          weight: 400
        - asset: assets/fonts/inter_24pt_regular.ttf
          weight: 400
        - asset: assets/fonts/inter_28pt_regular.ttf
          weight: 400
  uses-material-design: true
  generate: true